### ISSUE TITLE
Project initialization

### ISSUE THREAD

**Issue by siposm** [bprof-projm/wman#1]
- discuss technologies for frontend and backend
- create base project (backend and/or frontend)
- discuss classes / entities
- add gitignore to fit project needs
- create prototype (basic hello world for frontend and backend)

EST 5

**Comment by siposm** [comment]
@luxz97 is it CLOSED or OPEN? or you just accidentally re-opened it?! 🙂 

because it is in the DONE column, but the ticket is open. --> it's not good, please check it.

@tsaskater also Peti pls always dedicate a bit time to check the board / ticket statuses. 🙂

**Comment by luxz97** [comment]
![Képkivágás](https://user-images.githubusercontent.com/52691317/135253924-1f30a8b6-ae77-4bdb-9cfe-c3481e8a0627.PNG)
It was open initially, and I accidentaly closed it. I just wanted to close this window, and the close issue button was unfortunate enough to get under my mouse first. :)

**Comment by pop-simon** [comment]
I have closed the issue :)
